"""Make twitter_post column text

Revision ID: 61804b6c466c
Revises: 20260325_01
Create Date: 2026-03-29 18:03:32.456452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61804b6c466c'
down_revision = '20260325_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generations', 'twitter_post',
               existing_type=sa.VARCHAR(length=280),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generations', 'twitter_post',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=280),
               existing_nullable=True)
    # ### end Alembic commands ###
